### ISSUE TITLE
GLM and other homebrew build errors

### ISSUE THREAD

**Issue by stachowskitim** [pemsley/coot#167]
Just getting around to updating my Coot1 for FLEXR...

from a fresh fork on MacOS 14 using homebrew, this new bit in `configure.ac` makes it so it can't find `glm`. 

If I replace it with the original `PKG_CHECK_MODULES(GLM, glm >= 0.9.9)` it moves along. 

```
# While GLM has no pkgconfig glm.pc file, we have to be a bit more hand-to-mouth
# about its configuration
# PKG_CHECK_MODULES(GLM, glm >= 0.9.9)

# Copied and adapted from how gemmi and rdkit are found below
AC_ARG_WITH([glm], AS_HELP_STRING([--with-glm location of the GLM package]), with_glm="$withval", with_glm=false)

AC_MSG_CHECKING([for GLM])
if test "x$with_glm" = xfalse ; then
   if test -x $prefix/include/glm ; then
      #echo OK, good we found glm in $prefix
      AC_MSG_RESULT(yes)
      glm_install_dir=$prefix
      AC_SUBST(GLM_CXXFLAGS, "-I$glm_install_dir/include")
      AC_SUBST(GLM_LIBS, "-L$glm_install_dir/lib -lglm")
   else
      AC_MSG_RESULT(no)
      echo Configuration error. Could not find GLM.
      exit 1
   fi
else
   AC_MSG_RESULT(yes)
   AC_SUBST(GLM_CXXFLAGS, "-I$withval/include")
   AC_SUBST(GLM_LIBS, "-L$withval/lib -lglm")
fi
```

Then the build crashes with: 

```
Last 15 lines from /Users/tstachow/Library/Logs/Homebrew/coot/09.make:
      |                                ^
1 error generated.
make[1]: *** [key-bindings.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
mv -f .deps/gtk-manual.Tpo .deps/gtk-manual.Plo
libtool: compile:  clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.x-pre\" "-DPACKAGE_STRING=\"coot 1.1.x-pre\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.x-pre\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/Cellar/pcre2/10.44/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/glib/2.82.1/include -I/opt/homebrew/Cellar/glib/2.82.1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/include/graphene-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/opt/homebrew/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/opt/homebrew/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/opt/homebrew/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS -DHAVE_SYS_STDTYPES_H=0 -DUSE_MOLECULES_TO_TRIANGLES -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE -I/opt/homebrew/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/opt/homebrew/Cellar/libccp4/542516076_2/include -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000 -DUSE_SQLITE3 -I/opt/homebrew/opt/sqlite/include -DUSE_BACKWARD -I/opt/homebrew/opt/clipper4coot/fftw2/include -DUSE_MOLECULES_TO_TRIANGLES -DPKGDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot\" -DPACKAGE_LOCALE_DIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot/locale\" -DPKGPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/coot\" -DPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages\" -DXDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share\" -DCOOT_SYS_BUILD_TYPE=\"Darwin-MacOSX-14.7-arm64-gtk4\" -DCOOT_BUILD_INFO_STRING=\"\" -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0 -I/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -g -O2 -Wall -Wno-unused -std=c++17 -MT lbg-callbacks-outer.lo -MD -MP -MF .deps/lbg-callbacks-outer.Tpo -c lbg-callbacks-outer.cc -o lbg-callbacks-outer.o >/dev/null 2>&1
libtool: compile:  clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.x-pre\" "-DPACKAGE_STRING=\"coot 1.1.x-pre\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.x-pre\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/Cellar/pcre2/10.44/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/glib/2.82.1/include -I/opt/homebrew/Cellar/glib/2.82.1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/include/graphene-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/opt/homebrew/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/opt/homebrew/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/opt/homebrew/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS -DHAVE_SYS_STDTYPES_H=0 -DUSE_MOLECULES_TO_TRIANGLES -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE -I/opt/homebrew/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/opt/homebrew/Cellar/libccp4/542516076_2/include -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000 -DUSE_SQLITE3 -I/opt/homebrew/opt/sqlite/include -DUSE_BACKWARD -I/opt/homebrew/opt/clipper4coot/fftw2/include -DUSE_MOLECULES_TO_TRIANGLES -DPKGDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot\" -DPACKAGE_LOCALE_DIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot/locale\" -DPKGPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/coot\" -DPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages\" -DXDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share\" -DCOOT_SYS_BUILD_TYPE=\"Darwin-MacOSX-14.7-arm64-gtk4\" -DCOOT_BUILD_INFO_STRING=\"\" -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0 -I/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -g -O2 -Wall -Wno-unused -std=c++17 -MT LigandViewMesh.lo -MD -MP -MF .deps/LigandViewMesh.Tpo -c LigandViewMesh.cc -o LigandViewMesh.o >/dev/null 2>&1
mv -f .deps/lbg-callbacks-outer.Tpo .deps/lbg-callbacks-outer.Plo
mv -f .deps/graphics-ligand-mesh-molecule.Tpo .deps/graphics-ligand-mesh-molecule.Plo
mv -f .deps/LinesMesh.Tpo .deps/LinesMesh.Plo
mv -f .deps/LigandViewMesh.Tpo .deps/LigandViewMesh.Plo
libtool: compile:  clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.x-pre\" "-DPACKAGE_STRING=\"coot 1.1.x-pre\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.x-pre\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/Cellar/pcre2/10.44/include -I/opt/homebrew/Cellar/xz/5.6.3/include -I/opt/homebrew/Cellar/glib/2.82.1/include -I/opt/homebrew/Cellar/glib/2.82.1/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.82.1/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/libxcb/1.17.0/include -I/opt/homebrew/Cellar/libx11/1.8.10/include -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.18.2/include/cairo -I/opt/homebrew/Cellar/jpeg-turbo/3.0.4/include -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/Cellar/libtiff/4.7.0/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/fribidi/1.0.16/include/fribidi -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.54.0/include/pango-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/include/graphene-1.0 -I/opt/homebrew/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/opt/homebrew/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/opt/homebrew/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/opt/homebrew/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/opt/homebrew/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS -DHAVE_SYS_STDTYPES_H=0 -DUSE_MOLECULES_TO_TRIANGLES -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE -I/opt/homebrew/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/opt/homebrew/Cellar/libccp4/542516076_2/include -I/opt/homebrew/Cellar/mmdb2/2.0.22/include -I/opt/homebrew/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000 -DUSE_SQLITE3 -I/opt/homebrew/opt/sqlite/include -DUSE_BACKWARD -I/opt/homebrew/opt/clipper4coot/fftw2/include -DUSE_MOLECULES_TO_TRIANGLES -DPKGDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot\" -DPACKAGE_LOCALE_DIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share/coot/locale\" -DPKGPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/coot\" -DPYTHONDIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages\" -DXDATADIR=\"/opt/homebrew/Cellar/coot/HEAD-508303a/share\" -DCOOT_SYS_BUILD_TYPE=\"Darwin-MacOSX-14.7-arm64-gtk4\" -DCOOT_BUILD_INFO_STRING=\"\" -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0 -I/opt/homebrew/Cellar/coot/HEAD-508303a/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -g -O2 -Wall -Wno-unused -std=c++17 -MT init-from-gtkbuilder.lo -MD -MP -MF .deps/init-from-gtkbuilder.Tpo -c init-from-gtkbuilder.cc -o init-from-gtkbuilder.o >/dev/null 2>&1
mv -f .deps/gtk-utils.Tpo .deps/gtk-utils.Plo
mv -f .deps/init-from-gtkbuilder.Tpo .deps/init-from-gtkbuilder.Plo
make: *** [all-recursive] Error 1`
```

**Comment by stachowskitim** [comment]
Also, if install from the homebrew hosted formula, it builds (very quickly) but I get an `rdkit` error when I try to launch the GUI:

```
Library not loaded: /opt/homebrew/opt/rdkit/lib/libRDKitcoordgen.1.dylib
  Referenced from: <73CC3838-885F-32AC-B8AB-D09027406DF7> /opt/homebrew/Cellar/coot/1.1.10/libexec/MacCoot
  Reason: tried: '/opt/homebrew/opt/rdkit/lib/libRDKitcoordgen.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/rdkit/lib/libRDKitcoordgen.1.dylib' (no such file), '/opt/homebrew/opt/rdkit/lib/libRDKitcoordgen.1.dylib' (no such file), '/opt/homebrew/Cellar/rdkit/2024.09.1/lib/libRDKitcoordgen.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/rdkit/2024.09.1/lib/libRDKitcoordgen.1.dylib' (no such file), '/opt/homebrew/Cellar/rdkit/2024.09.1/lib/libRDKitcoordgen.1.dylib' (no such file)
/opt/homebrew/bin/coot: line 7: 94856 Abort trap: 6           ${exec_prefix}/libexec/MacCoot "$@"
```

**Comment by YoshitakaMo** [comment]
@stachowskitim and @pemsley,

At the moment, libRDKitcoordgen does not seem to be available in the latest RDKit.

```
libtool: link: clang++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libcoot-lidia-core.0.dylib .libs/libcoot-lidia-core.0.dylib-master.o  ../geometry/.libs/libcoot-geometry.dylib -L/usr/local/Cellar/libccp4/542516076_2/lib -L/usr/local/Cellar/mmdb2/2.0.22/lib -L/usr/local/Cellar/clipper4coot/2.1.20180802_3/lib -L/usr/local/Cellar/dwarfutils/0.11.0/lib ../utils/.libs/libcoot-utils.dylib ../mini-mol/.libs/libcoot-mini-mol.dylib -lclipper-ccp4 -lclipper-cif -lclipper-minimol -lclipper-mmdb -lclipper-cns -lclipper-phs -lclipper-contrib -lclipper-core -lccp4c -lmmdb2 -L/usr/local/opt/rdkit/lib -lRDKitMolDraw2D -lRDKitForceFieldHelpers -lRDKitDescriptors -lRDKitForceField -lRDKitSubstructMatch -lRDKitOptimizer -lRDKitDistGeomHelpers -lRDKitDistGeometry -lRDKitChemReactions -lRDKitAlignment -lRDKitEigenSolvers -lRDKitDepictor -lRDKitcoordgen -lRDKitMolChemicalFeatures -lRDKitFileParsers -lRDKitRDGeometryLib -lRDKitGraphMol -lRDKitShapeHelpers -lRDKitFingerprints -lRDKitMolAlign -lRDKitMolTransforms -lRDKitChemTransforms -lRDKitSmilesParse -lRDKitGenericGroups -lRDKitRingDecomposerLib -lRDKitFilterCatalog -lRDKitCatalogs -lRDKitSubgraphs -lRDKitPartialCharges -lRDKitRDGeneral -lRDKitDataStructs -lboost_serialization -lboost_iostreams -L/usr/local/opt/boost/lib -L/usr/local/opt/sqlite/lib -lsqlite3  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/coot/1.1.10/lib/libcoot-mini-mol.0.dylib:/private/tmp/coot-20241016-82372-tsp141/coot-1.1.10/mini-mol/.libs/libcoot-mini-mol.dylib -Wl,-dylib_file -Wl,/usr/local/Cellar/coot/1.1.10/lib/libcoot-utils.0.dylib:/private/tmp/coot-20241016-82372-tsp141/coot-1.1.10/utils/.libs/libcoot-utils.dylib -Wl,-dylib_file -Wl,/usr/local/Cellar/coot/1.1.10/lib/libcoot-compat.0.dylib:/private/tmp/coot-20241016-82372-tsp141/coot-1.1.10/compat/.libs/libcoot-compat.dylib -Wl,-dylib_file -Wl,/usr/local/Cellar/coot/1.1.10/lib/libcoot-utils.0.dylib:/private/tmp/coot-20241016-82372-tsp141/coot-1.1.10/utils/.libs/libcoot-utils.dylib   -pthread -install_name  /usr/local/Cellar/coot/1.1.10/lib/libcoot-lidia-core.0.dylib -compatibility_version 1 -current_version 1.0
ld: library 'RDKitcoordgen' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libcoot-lidia-core.la] Error 1
make: *** [all-recursive] Error 1
```

Probably this issue is introduced by [this PR for Homebrew's rdkit](https://github.com/Homebrew/homebrew-core/pull/192235). Now that `-DMAEPARSER_FORCE_BUILD=ON` and `-DCOORDGEN_FORCE_BUILD=ON` are removed (See https://github.com/Homebrew/homebrew-core/pull/192286/commits/021b9adbe4dce76bdc5180f38a3363c303cab227), I guess libRDKitcoordgen is not built.

I don't know how the library is incorporated in Coot, but if `libRDKitcoordgen` can be completely altered by `libcoordgen` of [Schrodinger's coordgenlibs](https://github.com/schrodinger/coordgenlibs), the installation of Coot is not difficult with it.

```
brew install coordgen
sed -i -e "s/RDKitcoordgen/coordgen/g" ./configure.ac (or ./configure)
```

But I do not guarantee that this will work correctly. If this trick works, it would be easy to rebuild Homebrew's coot. I would like to hear your opinion.

**Comment by YoshitakaMo** [comment]
Unfortunately, the trick failed after a long compilation process:

```
libtool: compile:  clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" "-DPACKAGE_STRING=\"coot 1.1.10\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -mfpmath=sse -msse -msse2 -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.15.0/include -I/usr/local/Cellar/pcre2/10.44/include -I/usr/local/Cellar/xz/5.6.3/include -I/usr/local/Cellar/glib/2.82.1/include -I/usr/local/Cellar/glib/2.82.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.82.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libxau/1.0.11/include -I/usr/local/Cellar/libxdmcp/1.1.5/include -I/usr/local/Cellar/libxcb/1.17.0/include -I/usr/local/Cellar/libx11/1.8.10/include -I/usr/local/Cellar/libxext/1.3.6/include -I/usr/local/Cellar/libxrender/0.9.11/include -I/usr/local/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/cairo/1.18.2/include/cairo -I/usr/local/Cellar/jpeg-turbo/3.0.4/include -I/usr/local/opt/zstd/include -I/usr/local/Cellar/libtiff/4.7.0/include -I/usr/local/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/fribidi/1.0.16/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/usr/local/Cellar/pango/1.54.0/include/pango-1.0 -I/usr/local/Cellar/graphene/1.10.8/include/graphene-1.0 -I/usr/local/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/usr/local/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/usr/local/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/usr/local/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/local/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS -DHAVE_SYS_STDTYPES_H=0 -DUSE_MOLECULES_TO_TRIANGLES -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/usr/local/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE -I/usr/local/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/usr/local/Cellar/libccp4/542516076_2/include -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000 -DUSE_SQLITE3 -I/usr/local/opt/sqlite/include -DUSE_BACKWARD -I/usr/local/opt/clipper4coot/fftw2/include -DUSE_MOLECULES_TO_TRIANGLES -DPKGDATADIR=\"/usr/local/Cellar/coot/1.1.10/share/coot\" -DPACKAGE_LOCALE_DIR=\"/usr/local/Cellar/coot/1.1.10/share/coot/locale\" -DPKGPYTHONDIR=\"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/coot\" -DPYTHONDIR=\"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages\" -DXDATADIR=\"/usr/local/Cellar/coot/1.1.10/share\" -DCOOT_SYS_BUILD_TYPE=\"Darwin-MacOSX-14.7-x86_64-gtk4\" -DCOOT_BUILD_INFO_STRING=\"\" -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0 -I/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include -I/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -g -O2 -Wall -Wno-unused -std=c++17 -MT LinesMesh.lo -MD -MP -MF .deps/LinesMesh.Tpo -c LinesMesh.cc  -fno-common -DPIC -o .libs/LinesMesh.o
/bin/sh ../libtool  --tag=CXX   --mode=compile clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" -DPACKAGE_STRING=\"coot\ 1.1.10\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_THREAD=/\*\*/ -DHAVE_BOOST_PYTHON=/\*\*/ -I.  -DUSE_PYTHON -mfpmath=sse -msse -msse2 -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.15.0/include -I/usr/local/Cellar/pcre2/10.44/include -I/usr/local/Cellar/xz/5.6.3/include -I/usr/local/Cellar/glib/2.82.1/include -I/usr/local/Cellar/glib/2.82.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.82.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libxau/1.0.11/include -I/usr/local/Cellar/libxdmcp/1.1.5/include -I/usr/local/Cellar/libxcb/1.17.0/include -I/usr/local/Cellar/libx11/1.8.10/include -I/usr/local/Cellar/libxext/1.3.6/include -I/usr/local/Cellar/libxrender/0.9.11/include -I/usr/local/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/cairo/1.18.2/include/cairo -I/usr/local/Cellar/jpeg-turbo/3.0.4/include -I/usr/local/opt/zstd/include -I/usr/local/Cellar/libtiff/4.7.0/include -I/usr/local/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/fribidi/1.0.16/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/usr/local/Cellar/pango/1.54.0/include/pango-1.0 -I/usr/local/Cellar/graphene/1.10.8/include/graphene-1.0 -I/usr/local/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/usr/local/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/usr/local/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/usr/local/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/local/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS  -DHAVE_SYS_STDTYPES_H=0   -DUSE_MOLECULES_TO_TRIANGLES -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/usr/local/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE  -I/usr/local/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/usr/local/Cellar/libccp4/542516076_2/include -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000       -DUSE_SQLITE3 -I/usr/local/opt/sqlite/include  -DUSE_BACKWARD  -I/usr/local/opt/clipper4coot/fftw2/include  -DUSE_MOLECULES_TO_TRIANGLES  -DPKGDATADIR='"/usr/local/Cellar/coot/1.1.10/share/coot"' -DPACKAGE_LOCALE_DIR='"/usr/local/Cellar/coot/1.1.10/share/coot/locale"' -DPKGPYTHONDIR='"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/coot"' -DPYTHONDIR='"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages"' -DXDATADIR='"/usr/local/Cellar/coot/1.1.10/share"' -DCOOT_SYS_BUILD_TYPE='"Darwin-MacOSX-14.7-x86_64-gtk4"' -DCOOT_BUILD_INFO_STRING='""'  -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0   -I/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include  -I/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13    -g -O2 -Wall -Wno-unused  -std=c++17 -MT lbg-interface.lo -MD -MP -MF .deps/lbg-interface.Tpo -c -o lbg-interface.lo lbg-interface.cc
mv -f .deps/graphics-info-modelling.Tpo .deps/graphics-info-modelling.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" -DPACKAGE_STRING=\"coot\ 1.1.10\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_THREAD=/\*\*/ -DHAVE_BOOST_PYTHON=/\*\*/ -I.  -DUSE_PYTHON -mfpmath=sse -msse -msse2 -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.15.0/include -I/usr/local/Cellar/pcre2/10.44/include -I/usr/local/Cellar/xz/5.6.3/include -I/usr/local/Cellar/glib/2.82.1/include -I/usr/local/Cellar/glib/2.82.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.82.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libxau/1.0.11/include -I/usr/local/Cellar/libxdmcp/1.1.5/include -I/usr/local/Cellar/libxcb/1.17.0/include -I/usr/local/Cellar/libx11/1.8.10/include -I/usr/local/Cellar/libxext/1.3.6/include -I/usr/local/Cellar/libxrender/0.9.11/include -I/usr/local/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/cairo/1.18.2/include/cairo -I/usr/local/Cellar/jpeg-turbo/3.0.4/include -I/usr/local/opt/zstd/include -I/usr/local/Cellar/libtiff/4.7.0/include -I/usr/local/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/fribidi/1.0.16/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/usr/local/Cellar/pango/1.54.0/include/pango-1.0 -I/usr/local/Cellar/graphene/1.10.8/include/graphene-1.0 -I/usr/local/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/usr/local/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/usr/local/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/usr/local/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/local/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS  -DHAVE_SYS_STDTYPES_H=0   -DUSE_MOLECULES_TO_TRIANGLES -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/usr/local/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE  -I/usr/local/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/usr/local/Cellar/libccp4/542516076_2/include -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000       -DUSE_SQLITE3 -I/usr/local/opt/sqlite/include  -DUSE_BACKWARD  -I/usr/local/opt/clipper4coot/fftw2/include  -DUSE_MOLECULES_TO_TRIANGLES  -DPKGDATADIR='"/usr/local/Cellar/coot/1.1.10/share/coot"' -DPACKAGE_LOCALE_DIR='"/usr/local/Cellar/coot/1.1.10/share/coot/locale"' -DPKGPYTHONDIR='"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/coot"' -DPYTHONDIR='"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages"' -DXDATADIR='"/usr/local/Cellar/coot/1.1.10/share"' -DCOOT_SYS_BUILD_TYPE='"Darwin-MacOSX-14.7-x86_64-gtk4"' -DCOOT_BUILD_INFO_STRING='""'  -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0   -I/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include  -I/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13    -g -O2 -Wall -Wno-unused  -std=c++17 -MT Model.lo -MD -MP -MF .deps/Model.Tpo -c -o Model.lo Model.cc
libtool: compile:  clang++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" "-DPACKAGE_STRING=\"coot 1.1.10\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.13\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -mfpmath=sse -msse -msse2 -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.15.0/include -I/usr/local/Cellar/pcre2/10.44/include -I/usr/local/Cellar/xz/5.6.3/include -I/usr/local/Cellar/glib/2.82.1/include -I/usr/local/Cellar/glib/2.82.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.82.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libxau/1.0.11/include -I/usr/local/Cellar/libxdmcp/1.1.5/include -I/usr/local/Cellar/libxcb/1.17.0/include -I/usr/local/Cellar/libx11/1.8.10/include -I/usr/local/Cellar/libxext/1.3.6/include -I/usr/local/Cellar/libxrender/0.9.11/include -I/usr/local/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/cairo/1.18.2/include/cairo -I/usr/local/Cellar/jpeg-turbo/3.0.4/include -I/usr/local/opt/zstd/include -I/usr/local/Cellar/libtiff/4.7.0/include -I/usr/local/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/fribidi/1.0.16/include/fribidi -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/harfbuzz/10.0.1_1/include/harfbuzz -I/usr/local/Cellar/pango/1.54.0/include/pango-1.0 -I/usr/local/Cellar/graphene/1.10.8/include/graphene-1.0 -I/usr/local/Cellar/graphene/1.10.8/lib/graphene-1.0/include -I/usr/local/Cellar/gtk4/4.16.3/include/gtk-4.0 -I/usr/local/Cellar/xorgproto/2024.1/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I.. -I/usr/local/opt/rdkit/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/local/opt/boost/include -DMAKE_ENHANCED_LIGAND_TOOLS -DHAVE_SYS_STDTYPES_H=0 -DUSE_MOLECULES_TO_TRIANGLES -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/ssm/1.4_2/include -DHAVE_SSMLIB -I/usr/local/Cellar/mmdb2/2.0.22/include -DMMDB_HAS_LINK_DISTANCE -I/usr/local/Cellar/gsl/2.8/include -D_THREAD_SAFE -pthread -I/usr/local/Cellar/libccp4/542516076_2/include -I/usr/local/Cellar/mmdb2/2.0.22/include -I/usr/local/Cellar/clipper4coot/2.1.20180802_3/include -DCLIPPER_HAS_TOP8000 -DUSE_SQLITE3 -I/usr/local/opt/sqlite/include -DUSE_BACKWARD -I/usr/local/opt/clipper4coot/fftw2/include -DUSE_MOLECULES_TO_TRIANGLES -DPKGDATADIR=\"/usr/local/Cellar/coot/1.1.10/share/coot\" -DPACKAGE_LOCALE_DIR=\"/usr/local/Cellar/coot/1.1.10/share/coot/locale\" -DPKGPYTHONDIR=\"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/coot\" -DPYTHONDIR=\"/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages\" -DXDATADIR=\"/usr/local/Cellar/coot/1.1.10/share\" -DCOOT_SYS_BUILD_TYPE=\"Darwin-MacOSX-14.7-x86_64-gtk4\" -DCOOT_BUILD_INFO_STRING=\"\" -DUSE_LIBCURL -DHAVE_SYS_STDTYPES_H=0 -I/usr/local/Cellar/coot/1.1.10/lib/python3.13/site-packages/PyGObject-3.42.2-py3.9-linux-x86_64.egg/include -I/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -g -O2 -Wall -Wno-unused -std=c++17 -MT LigandViewMesh.lo -MD -MP -MF .deps/LigandViewMesh.Tpo -c LigandViewMesh.cc  -fno-common -DPIC -o .libs/LigandViewMesh.o
key-bindings.cc:55:32: error: use of undeclared identifier 'PyEval_CallObject'
   55 |          PyObject *result_py = PyEval_CallObject(function_py, arg_list);
      |                                ^
1 error generated.
make[1]: *** [key-bindings.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by pemsley** [comment]
Related to this, I guess?

https://github.com/python/cpython/issues/105107

**Comment by pemsley** [comment]
OK, I have pushed what I think is a fix: 26c08247673834ba561feeb9260c4f1f339ef4b5

**Comment by YoshitakaMo** [comment]
@pemsley I've successfully built Coot 1.1.10 again with Schrodinger's `coordgen` package and some patches to use it.

```shell
    # Use libcoordgen instead of RDKitcoordgen
    inreplace "configure.ac", "RDKitcoordgen", "coordgen"
    # patch
    inreplace "src/key-bindings.cc",
              "PyObject *result_py = PyEval_CallObject(function_py, arg_list);",
              "PyObject *result_py = PyObject_Call(function_py, arg_list, nullptr);"
```

The users can install Coot 1.1.10 with `brew install brewsci/bio/coot` again. However, the installation with `--HEAD` (latest commit one) still fails due to the GLM error. Please consider incorporating them for 1.1.11 release.

**Comment by stachowskitim** [comment]
Just confirming I see the same thing as @YoshitakaMo on my end, except from the `brewsci/bio/coot` install, the `Fetch PDB and Map from the EDS` function still doesn't seem to work - no model and map show up, although the command line says things are successful.

**Comment by pemsley** [comment]
@stachowskitim 
Yes. Oliver Clarke is on the case!
https://github.com/pemsley/coot/issues/165

**Comment by pemsley** [comment]
@hgonomeg What do you recommend for testing for coordgen usage in the RDKit?

**Comment by YoshitakaMo** [comment]
@pemsley I am rebuilding a homebrew bottle for macOS Sequoia users. However, I've encountered some fatal issues. 
When I selected "Load tutorial model & Data" after the Homebrew installation, the model was not displayed at all probably because of some errors.

```
INFO:: Stored refmac parameters: FGMP18 SIGFGMP18 FreeR_flag is sensible.
INFO:: making map from mtz filename /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz
INFO:: Number of observed reflections: 17554
INFO:: finding ASU unique map points with sampling rate 2.5
INFO:: grid sampling...Nuvw = ( 180, 216, 108)
      Map extents: ..... 180 216 108
      Map mean: ........ 8.80115e-06
      Map sigma: ....... 0.173602
      Map maximum: ..... 2.78252
      Map minimum: ..... -1.78282
DEBUG:: --- new_startup_on_glarea_resize() 1228 1364
error draw_rotation_centre_crosshairs() A0 err 1286
render_3d_scene lambda B err 1286
error::draw_central_cube() F glDrawElements() err 1286
GL ERROR:: You forgot to setup this Mesh: "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version" meshes.shader
error:: Mesh::draw() meshes.shader /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version glBindVertexArray() vao 99999999 with GL err 1282
GL ERROR:: draw() glBindBuffer() Mesh::draw() post-vertex arrays shader meshes.shader error 1282
GL ERROR:: draw() glDrawElements() of Mesh "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version" shader: meshes.shader vao 99999999 n_verts_for_gl_lines 161682 with GL err 1282
draw_map_molecules() --- draw map loop start --- error
GL ERROR:: You forgot to setup this Mesh: "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version" meshes.shader
error:: Mesh::draw() meshes.shader /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version glBindVertexArray() vao 99999999 with GL err 1282
GL ERROR:: draw() glBindBuffer() Mesh::draw() post-vertex arrays shader meshes.shader error 1282
GL ERROR:: draw() glDrawElements() of Mesh "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version" shader: meshes.shader vao 99999999 n_verts_for_gl_lines 1058058 with GL err 1282
GL ERROR:: g.draw_map_molecules() -- start -- 1282
DEBUG:: --- new_startup_on_glarea_resize() 1344 1364
error draw_rotation_centre_crosshairs() A0 err 1286
render_3d_scene lambda B err 1286
error::draw_central_cube() F glDrawElements() err 1286
GL ERROR:: You forgot to setup this Mesh: "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version" meshes.shader
error:: Mesh::draw() meshes.shader /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version glBindVertexArray() vao 99999999 with GL err 1282
GL ERROR:: draw() glBindBuffer() Mesh::draw() post-vertex arrays shader meshes.shader error 1282
GL ERROR:: draw() glDrawElements() of Mesh "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version" shader: meshes.shader vao 99999999 n_verts_for_gl_lines 1058058 with GL err 1282
GL ERROR:: g.draw_map_molecules() -- start -- 1282
DEBUG:: --- new_startup_on_glarea_resize() 1646 1368
error draw_rotation_centre_crosshairs() A0 err 1286
render_3d_scene lambda B err 1286
error::draw_central_cube() F glDrawElements() err 1286
GL ERROR:: You forgot to setup this Mesh: "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version" meshes.shader
error:: Mesh::draw() meshes.shader /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version glBindVertexArray() vao 99999999 with GL err 1282
GL ERROR:: draw() glBindBuffer() Mesh::draw() post-vertex arrays shader meshes.shader error 1282
GL ERROR:: draw() glDrawElements() of Mesh "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz DELFWT PHDELWT gl-lines-version" shader: meshes.shader vao 99999999 n_verts_for_gl_lines 161682 with GL err 1282
draw_map_molecules() --- draw map loop start --- error
GL ERROR:: You forgot to setup this Mesh: "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version" meshes.shader
error:: Mesh::draw() meshes.shader /opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version glBindVertexArray() vao 99999999 with GL err 1282
GL ERROR:: draw() glBindBuffer() Mesh::draw() post-vertex arrays shader meshes.shader error 1282
GL ERROR:: draw() glDrawElements() of Mesh "/opt/homebrew/Cellar/coot/1.1.10_1/share/coot/data/rnasa-1.8-all_refmac1.mtz FWT PHWT gl-lines-version" shader: meshes.shader vao 99999999 n_verts_for_gl_lines 1058058 with GL err 1282
GL ERROR:: g.draw_map_molecules() -- start -- 1282
DEBUG:: --- new_startup_on_glarea_resize() 1648 1364
error draw_rotation_centre_crosshairs() A0 err 1286
render_3d_scene lambda B err 1286
```

I guess this error may not be due to Sequoia and the OS itself but some recent updates for the dependent packages, such as Python 3.13, Rdkit, or Pygobject. Do you have any ideas on how to fix it?

**Comment by pemsley** [comment]
I think that it's all my fault.

The crosshairs have disappeared for me on Sonoma.
I've been meaning to find some time to look at it - but travel makes that basically impossible.
Interesting that you get error messages.

**Comment by stachowskitim** [comment]
I'm working on integrating FLEXR into Coot 1.1.10, but it looks like the extensions are broken:

from an install with `brew install coot` on macOS Sonoma 14.7

if I try to load the "Refine", "CCP4", or "CryoEM" extensions, I get the following error"

```
debug:: safe_python_command() PyRun_SimpleString() import gui_prosmart
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/coot/gui_prosmart.py", line 26, in <module>
    import coot_gui_api
ModuleNotFoundError: No module named 'coot_gui_api'
debug:: safe_python_command() PyRun_SimpleString() gui_prosmart.add_module_restraints()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'gui_prosmart' is not defined
```
    
In general, I'm hoping to send an easy pull request, is it worth working off the `Release-1.1.10` tag or do you recommend something else?

**Comment by pemsley** [comment]
I should make a release soon.

Second, I have problems with python (gtk?) modules too on my own machine.

It's all a bit frustrating.
